### PR TITLE
fixed filtering of interesting events

### PR DESCRIPTION
**Pull request by gitoleg**
Fixed filtering of interesting events, to be sure that unsupported events will not break anything, e.g. statistic.

### CODE REVIEW

**Comment by gitoleg** [comment]
As for now `veri` is able to product a set of artificial events, that were enumerated in function in question. So if we will decide to ignore some events on policy level, then we will have to include a one rule for every ignored event to every file with policies, and that is why I suggest to do it in code.

**Comment by ivg** [comment]
I don't think that ignoring events in policy files is a bad idea. Especially, if we will be able to use regular expressions for this.

**Comment by gitoleg** [comment]
Ok, then it's time to write a more verbose `pp` for our event types to use it with policy

**Comment by gitoleg** [comment]
done

**Pull request merged**
